version: "3.1"

volumes:
  db_data: {}

services:
  db:
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    env_file:
      - .env
    volumes:
      - ./dist:/app/dist
      - ./prisma:/app/prisma
    ports:
      - "3000:3000"